version: "3.5"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  server:
    build: ./
    ports:
      - 3001:3001
    links:
      - redis
    environment:
      - REDIS_SETTING_HOSTS=cache:6379
      - NODE_ENV=production
      - ENV=prod
